version: '3.8'

services:
  app:
    build: .
    ports:
      - "8866:8866"
    environment:
      - FLASK_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - redis
    volumes:
      - ./web_ui/config.db:/app/web_ui/config.db
      - ./qdii_tables:/app/qdii_tables

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
